function test_module2_transmon_trapped_charge_2d()
% TEST_MODULE2_TRANSMON_TRAPPED_CHARGE_2D Verify charged-defect response.
setup_project_paths;
params = default_module2_params('transmon_trapped_charge');
params.makePlots = false;
params.saveMat = false;
result = solve_poisson_defect_space_charge_2d(params);

leftNodes = result.geometry.tags.electrode.left_electrode.nodeIds(:);
rightNodes = result.geometry.tags.electrode.right_electrode.nodeIds(:);
assert(max(result.rho) > 0, ...
    'Transmon trapped-charge source must contain positive charge.');
assert(all(isfinite(result.phi)) && all(isfinite(result.field.Emag_nodal)), ...
    'Transmon trapped-charge solve contains non-finite values.');
assert(max(abs(result.phi([leftNodes; rightNodes]))) < 1e-12, ...
    'Grounded tagged electrodes were not held at zero potential.');
assert(max(result.phi) > 0, ...
    'Positive trapped charge should produce a positive potential perturbation.');
assert(min(result.phi) >= -1e-10 * max(result.phi), ...
    'Positive-source solution contains a significant negative potential.');
assert(result.diagnostics.freeResidualRelative < 1e-9, ...
    'Free-node residual is too large: %.3e', ...
    result.diagnostics.freeResidualRelative);
assert(result.diagnostics.globalBalanceRelative < 1e-9, ...
    'Global source/reaction balance is too large: %.3e', ...
    result.diagnostics.globalBalanceRelative);

fprintf(['test_module2_transmon_trapped_charge_2d passed: ', ...
    'max phi %.3e V, balance %.3e.\n'], ...
    max(result.phi), result.diagnostics.globalBalanceRelative);
end
