function test_module9_geometry_dimensions_2d()
% TEST_MODULE9_GEOMETRY_DIMENSIONS_2D Verify documented Module 9 dimensions.
setup_project_paths;
params = default_module9_transmon_geometry_2d();
geom = build_module9_transmon_geometry_2d(params);

% Verify the substrate dimensions and 1.5 mm^2 cross-sectional area in SI.
assert(abs(geom.domain.width - 3.0e-3) < 1e-12, ...
    'Module 9 substrate width is not 3 mm.');
assert(abs(geom.domain.thickness - 0.5e-3) < 1e-12, ...
    'Module 9 substrate thickness is not 0.5 mm.');
assert(abs(geom.domain.area - 1.5e-6) < 1e-15, ...
    'Module 9 substrate area is not 1.5 mm^2.');

% Verify the physical thin-film metadata retained outside the bulk mesh.
assert(abs(geom.thickness.aluminum - 100e-9) < 1e-15, ...
    'Aluminum thickness is not 100 nm.');
assert(abs(geom.thickness.normalTrap - 80e-9) < 1e-15, ...
    'Normal-trap thickness is not 80 nm.');
assert(abs(geom.thickness.backsideSink - 1e-6) < 1e-15, ...
    'Backside-sink effective thickness is not 1 um.');
assert(abs(diff(geom.regions.leftPad.zRange) - 100e-9) < 1e-15, ...
    'Left-pad physical z range does not retain the 100 nm Al thickness.');
assert(abs(geom.regions.normalTrap.zRange(1) - 100e-9) < 1e-15 && ...
    abs(diff(geom.regions.normalTrap.zRange) - 80e-9) < 1e-15, ...
    'Normal-trap physical z range is not stacked above the Al film.');

% Verify the headline lateral dimensions from the Module 9 physics note.
assert(abs(geom.reference.padGap.width - 60e-6) < 1e-12, ...
    'Nominal large-pad gap is not 60 um.');
assert(abs(geom.regions.leftPad.length - 600e-6) < 1e-12, ...
    'Left capacitor-pad width is not 600 um.');
assert(abs(geom.regions.rightPad.length - 600e-6) < 1e-12, ...
    'Right capacitor-pad width is not 600 um.');
assert(abs(geom.regions.jj.length - 1e-6) < 1e-12, ...
    'Effective JJ width is not 1 um.');
assert(abs(geom.regions.normalTrap.length - 100e-6) < 1e-12, ...
    'Normal-trap length is not 100 um.');
assert(abs(geom.regions.backsideSink.length - 300e-6) < 1e-12, ...
    'Backside-sink width is not 300 um.');

fprintf('test_module9_geometry_dimensions_2d passed.\n');
end
