function report = validate_module9_transmon_geometry_2d(geom, throwOnFailure)
% VALIDATE_MODULE9_TRANSMON_GEOMETRY_2D Check dimensions, tags, and topology.
%
%   report = VALIDATE_MODULE9_TRANSMON_GEOMETRY_2D(geom) returns a report and
%   throws an error if any check fails.  Pass false as the second argument to
%   collect a report without throwing, as the geometry builder does.

if nargin < 2 || isempty(throwOnFailure)
    throwOnFailure = true;
end

params = geom.params;
mesh = geom.mesh;
tags = geom.tags;
tolLength = 1e-12;
checks = struct('name', {}, 'passed', {}, 'value', {}, 'expected', {}, 'message', {});

% Check the documented substrate width, thickness, and cross-sectional area.
checks(end + 1) = make_check('substrate_width', ...
    abs(params.domain.width - 3.0e-3) <= tolLength, ...
    params.domain.width, 3.0e-3, 'Substrate width must be 3 mm.');
checks(end + 1) = make_check('substrate_thickness', ...
    abs(params.domain.thickness - 0.5e-3) <= tolLength, ...
    params.domain.thickness, 0.5e-3, 'Substrate thickness must be 0.5 mm.');
checks(end + 1) = make_check('substrate_area', ...
    abs(params.domain.area - 1.5e-6) <= 1e-15, ...
    params.domain.area, 1.5e-6, 'Substrate area must be 1.5 mm^2.');

% Confirm every geometric endpoint was inserted exactly into the mesh x vector.
requiredX = collect_required_x(params);
nearestErrors = zeros(size(requiredX));
for k = 1:numel(requiredX)
    nearestErrors(k) = min(abs(mesh.x - requiredX(k)));
end
checks(end + 1) = make_check('all_required_x_coordinates_present', ...
    max(nearestErrors) <= tolLength, max(nearestErrors), 0, ...
    'Every pad, lead, JJ, trap, bond-pad, and sink endpoint must be a mesh line.');

% Check that every triangle is non-degenerate and counter-clockwise.
p1 = mesh.nodes(mesh.elems(:, 1), :);
p2 = mesh.nodes(mesh.elems(:, 2), :);
p3 = mesh.nodes(mesh.elems(:, 3), :);
signedDoubleArea = (p2(:, 1) - p1(:, 1)) .* (p3(:, 2) - p1(:, 2)) - ...
    (p3(:, 1) - p1(:, 1)) .* (p2(:, 2) - p1(:, 2));
checks(end + 1) = make_check('positive_triangle_areas', ...
    all(signedDoubleArea > 0), min(signedDoubleArea) / 2, '> 0', ...
    'Every triangular element must have positive area and CCW node ordering.');

% Verify the intended connected central geometry by interval contact/overlap.
checks(end + 1) = interval_check('left_pad_touches_left_lead', ...
    params.regions.leftPad.xRange, params.regions.leftLead.xRange, tolLength);
checks(end + 1) = interval_check('left_lead_touches_jj', ...
    params.regions.leftLead.xRange, params.regions.jj.xRange, tolLength);
checks(end + 1) = interval_check('jj_touches_right_lead', ...
    params.regions.jj.xRange, params.regions.rightLead.xRange, tolLength);
checks(end + 1) = interval_check('right_lead_touches_right_pad', ...
    params.regions.rightLead.xRange, params.regions.rightPad.xRange, tolLength);

% Confirm the normal trap lies entirely within the right large pad and remains
% far from the left electrode, so it cannot bridge the two transmon nodes.
trapInRightPad = params.regions.normalTrap.xRange(1) >= ...
    params.regions.rightPad.xRange(1) - tolLength && ...
    params.regions.normalTrap.xRange(2) <= ...
    params.regions.rightPad.xRange(2) + tolLength;
checks(end + 1) = make_check('trap_contained_in_right_pad', ...
    trapInRightPad, params.regions.normalTrap.xRange, ...
    params.regions.rightPad.xRange, 'Normal trap must remain on the right pad.');
trapBridgesNodes = params.regions.normalTrap.xRange(1) <= ...
    params.regions.leftPad.xRange(2) + tolLength;
checks(end + 1) = make_check('trap_does_not_bridge_electrodes', ...
    ~trapBridgesNodes, trapBridgesNodes, false, ...
    'Normal trap must not touch or bridge the left electrode.');

% Compare every primary tag length with its exact analytical interval length.
checks(end + 1) = length_check('left_pad_tag_length', ...
    tags.top.left_pad.length, params.regions.leftPad.length, tolLength);
checks(end + 1) = length_check('right_pad_tag_length', ...
    tags.top.right_pad.length, params.regions.rightPad.length, tolLength);
checks(end + 1) = length_check('left_lead_tag_length', ...
    tags.top.left_lead.length, params.regions.leftLead.length, tolLength);
checks(end + 1) = length_check('jj_tag_length', ...
    tags.top.jj_sensitive.length, params.regions.jj.length, tolLength);
checks(end + 1) = length_check('right_lead_tag_length', ...
    tags.top.right_lead.length, params.regions.rightLead.length, tolLength);
checks(end + 1) = length_check('normal_trap_tag_length', ...
    tags.top.normal_trap.length, params.regions.normalTrap.length, tolLength);
checks(end + 1) = length_check('left_bond_pad_tag_length', ...
    tags.top.left_bond_pad.length, params.regions.leftBondPad.length, tolLength);
checks(end + 1) = length_check('right_bond_pad_tag_length', ...
    tags.top.right_bond_pad.length, params.regions.rightBondPad.length, tolLength);
checks(end + 1) = length_check('backside_sink_tag_length', ...
    tags.bottom.backside_sink.length, params.regions.backsideSink.length, tolLength);

% Check the key explicit dimensions called out in the physics note.
checks(end + 1) = make_check('pad_gap_width', ...
    abs(params.reference.padGap.width - 60e-6) <= tolLength, ...
    params.reference.padGap.width, 60e-6, 'Large-pad inner-edge gap must be 60 um.');
checks(end + 1) = make_check('jj_width', ...
    abs(params.regions.jj.length - 1e-6) <= tolLength, ...
    params.regions.jj.length, 1e-6, 'Effective JJ segment must be 1 um wide.');
checks(end + 1) = make_check('backside_sink_width', ...
    abs(params.regions.backsideSink.length - 300e-6) <= tolLength, ...
    params.regions.backsideSink.length, 300e-6, 'Backside sink must be 300 um wide.');
checks(end + 1) = make_check('bond_pad_widths', ...
    abs(params.regions.leftBondPad.length - 80e-6) <= tolLength && ...
    abs(params.regions.rightBondPad.length - 80e-6) <= tolLength, ...
    [params.regions.leftBondPad.length, params.regions.rightBondPad.length], ...
    [80e-6, 80e-6], 'Both baseline bond pads must be 80 um wide.');

% Confirm the stored z extents preserve the physical stack specification even
% though the substrate-only mesh does not resolve those thin layers.
filmStacksCorrect = abs(diff(params.regions.leftPad.zRange) - ...
    params.thickness.aluminum) <= tolLength && ...
    abs(params.regions.normalTrap.zRange(1) - params.thickness.aluminum) <= tolLength && ...
    abs(diff(params.regions.normalTrap.zRange) - params.thickness.normalTrap) <= tolLength && ...
    abs(diff(params.regions.backsideSink.zRange) - params.thickness.backsideSink) <= tolLength;
checks(end + 1) = make_check('thin_film_z_ranges_stored', ...
    filmStacksCorrect, filmStacksCorrect, true, ...
    'Al, normal-trap, and backside-sink physical z ranges must be retained.');

% Verify that the explicit modeling decision to omit curved wires was preserved.
wireOmitted = ~params.modeling.includeCurvedWireArcs && ...
    ~tags.omissions.curved_wire_arcs.present && ...
    ~isfield(params.regions, 'wireArc') && ~isfield(params.regions, 'wireArcs');
checks(end + 1) = make_check('curved_wire_arcs_omitted', ...
    wireOmitted, wireOmitted, true, ...
    'Curved bond-wire arcs must not exist as mesh regions or tags.');

% Verify that all stored tag edge IDs remain within their named boundary arrays.
tagIdsValid = all_tag_ids_valid(tags, mesh);
checks(end + 1) = make_check('tag_edge_ids_valid', ...
    tagIdsValid, tagIdsValid, true, 'Every tag edge ID must reference its stated side.');

% Summarize failures without discarding individual diagnostic values.
report.checks = checks;
report.passed = all([checks.passed]);
report.nChecks = numel(checks);
report.nPassed = sum([checks.passed]);
report.nFailed = report.nChecks - report.nPassed;
report.failedNames = {checks(~[checks.passed]).name};

% Throw only when requested, allowing the builder to retain a diagnostic report.
if throwOnFailure && ~report.passed
    error('Module9Geometry:ValidationFailed', ...
        'Module 9 geometry validation failed: %s', strjoin(report.failedNames, ', '));
end
end

function requiredX = collect_required_x(params)
% COLLECT_REQUIRED_X Return every coordinate that must be represented exactly.
requiredX = unique([ ...
    params.domain.xRange, params.regions.leftBondPad.xRange, ...
    params.regions.leftPad.xRange, params.regions.leftLead.xRange, ...
    params.reference.padGap.xRange, params.regions.jj.xRange, ...
    params.regions.rightLead.xRange, params.regions.rightPad.xRange, ...
    params.regions.normalTrap.xRange, params.regions.backsideSink.xRange, ...
    params.regions.rightBondPad.xRange]);
end

function check = interval_check(name, rangeA, rangeB, tol)
% INTERVAL_CHECK Check whether closed one-dimensional ranges touch or overlap.
gap = max(rangeA(1), rangeB(1)) - min(rangeA(2), rangeB(2));
check = make_check(name, gap <= tol, gap, '<= 0', ...
    'The two named central-metal intervals must touch or overlap.');
end

function check = length_check(name, actual, expected, tol)
% LENGTH_CHECK Compare a computed boundary length with its analytic value.
check = make_check(name, abs(actual - expected) <= tol, actual, expected, ...
    'Tagged boundary length must match the geometry specification.');
end

function check = make_check(name, passed, value, expected, message)
% MAKE_CHECK Create one uniform validation-record structure.
check.name = name;
check.passed = logical(passed);
check.value = value;
check.expected = expected;
check.message = message;
end

function valid = all_tag_ids_valid(tags, mesh)
% ALL_TAG_IDS_VALID Validate the primary tag IDs against boundary array sizes.
valid = true;
topNames = fieldnames(tags.top);
for k = 1:numel(topNames)
    ids = tags.top.(topNames{k}).edgeIds;
    valid = valid && all(ids >= 1 & ids <= size(mesh.boundaryEdges.top, 1));
end
bottomNames = fieldnames(tags.bottom);
for k = 1:numel(bottomNames)
    ids = tags.bottom.(bottomNames{k}).edgeIds;
    valid = valid && all(ids >= 1 & ids <= size(mesh.boundaryEdges.bottom, 1));
end
end
